name: Deploy to Firebase Hosting

# This workflow deploys the static-generated nextjs app to Firebase Hosting
# Triggered by push to the "dev" branch
on:
  push:
    branches:
      - dev
      - firebase-hosting

jobs:
  deploy-client:
    name: Deploy Client to Firebase Hosting
    needs: lint-export-client
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:webserver
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
